---
  title: "ICOM 2024"
---
  
Welcome! This page provides more details about my ICOM 2024 presentation.

Poster Number: Poster Number: **LT-068**

Poster Title: **Common Non-Mycorrhizal Networks: Exploring the “Dark Web”**

### Poster Session Details:

Poster Session Name: Poster Session 5

Poster Session Date & Time: **August 8, Thursday &  10:35 - 11:15**

### Lightning Talk Session Details:

Session Name: Plenary Session 3: Regulation and Transport in Mycorrhizal Networks

Session Date & Time: **August 8, Thursday & 10:35 - 11:15**


Find me! 

# R package I made for this experiment
**Bock**, B. https://github.com/beabock/nanodRop Zenodo https://doi.org/10.5281/ZENODO.12519996 **(2024)**.

- Made to deal with the output files from the NanoDrop One spectrophotometer (which I used for the spectral measurements).

# References

**DeMers**, M. Alternaria alternata as endophyte and pathogen. *Microbiology* 168, **(2022)**.

- Good overview of DSE used in this experiment (Alternaria sp., likely Alternaria alternata)


**Jumpponen, A. & Trappe**, J. M. Dark septate endophytes: a review of facultative biotrophic root‐colonizing fungi. *New Phytol.* 140, 295–310 **(1998)**.

- Good review on DSEs. Effects on plants can vary depending on conditions; DSE have little to no known host specificity.


**Netherway**, T. et al. Pervasive associations between dark septate endophytic fungi with tree root and soil microbiomes across Europe. *Nat. Commun.* 15, 159 **(2024)**.

- DSE root colonization shape tree-associated microbiomes.

- Structure of root and soil microbiomes across sites is more strongly and consistently associated with DSE colonization than with mycorrhizal colonization and many abiotic factors. 

- DSE root colonization has consistent neg association with nutrient cycling genes. 

- DSE may suppress plant pathogens. 

- "To better understand DSE associations, their importance, and potential applications, we need more research characterizing, isolating, culturing, and re-inoculating plant roots with DSE"


**Newman**, E. I. Mycorrhizal Links Between Plants: Their Functioning and Ecological Significance. *Adv. Ecol. Res.* 18, 243–270 **(1988)**.

- Early hypotheses regarding ecological impacts of common mycorrhizal networks.

**Newsham**, K. K. A meta‐analysis of plant responses to dark septate root endophytes. *New Phytol.* 190, 783–793 **(2011)**.

- DSE improve plant growth relative to sterile controls (total, shoot, and root biomass, shoot N and P). 

- DSE don't affect plant growth when inorganic N is supplied 


**Rillig**, M. C., Lehmann, A., Lanfranco, L., Caruso, T. & Johnson, D. Clarifying the definition of common mycorrhizal networks. *Funct. Ecol.* 1365-2435.14545 **(2024)** doi:10.1111/1365-2435.14545.

- Proposes the term of "Common Fungal Networks" with the idea that non-mycorrhizal fungi may form common networks in addition to those formed my mycorrhizal fungi
